services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ChatCluster

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=ChatCluster
      - CASSANDRA_SEEDS=cassandra1

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=ChatCluster
      - CASSANDRA_SEEDS=cassandra1